version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./client/client.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    command: "npm start"
  server:
    build:
      context: .
      dockerfile: ./server/server.Dockerfile
    user: node
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
    command: "npm start"
  
