version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./docker/client.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./client
        target: /usr/src/app
    command: "npm start"
  server:
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    user: node
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./server
        target: /usr/src/app
    command: "npm start"
  
